    Voice = {
        1: [
            { roll: [1], result: "Lispy" },
            { roll: range(2, 4), result: "Berry Kripkey (R's to W's)" },
            { roll: range(5, 7), result: "Childish" },
            { roll: range(8, 17), result: "Firm" },
            { roll: range(18, 21), result: "High Pitched" }, 				**With Voice2**
            { roll: range(22, 26), result: "Loud" }, 					**With Voice2**
            { roll: range(27, 30), result: "Low Pitched" }, 				**With Voice2**
            { roll: range(31, 45), result: "Normal" }, 					**With Voice2**
            { roll: range(46, 50), result: "Pirate" },
            { roll: range(51, 55), result: "Raspy" },
            { roll: range(56, 65), result: "Rough" }, 					**With Voice2**
            { roll: range(66, 70), result: "Smooth" }, 					**With Voice2**
            { roll: range(71, 80), result: "Soft" }, 					**With Voice2**
            { roll: range(81, 90), result: "Grog" },
            { roll: range(91, 100), result: "Wispy" },
        ],
        2: [
            { roll: range(1, 60), result: "No Accent" },
            { roll: range(61, 64), result: "Southern Accent" },
            { roll: range(65, 68), result: "New England Accent" },
            { roll: range(69, 72), result: "Minnesotta Accent" },
            { roll: range(73, 76), result: "Irish Accent" },
            { roll: range(77, 80), result: "German Accent" },
            { roll: range(81, 84), result: "French Accent" },
            { roll: range(85, 88), result: "English Accent (The Beattles)" },
            { roll: range(89, 90), result: "Dutch Accent" },
            { roll: range(91, 92), result: "Australian Accent" },
            { roll: range(93, 94), result: "Asian Accent" },
            { roll: range(95, 96), result: "Canadian Accent" },
            { roll: range(97, 98), result: "Indian Accent" },
            { roll: range(99, 100), result: "Native American Accent" },
        ],
    },

    Mannerisms = {
        1: [
            'Bites fingernails',
            'Chews something',
            'Dry washes hands',
            'Enunciates overly clearly',
            'Fidgets',
            'Frequently uses the wrong words',
            'Makes constant jokes or puns',
            'Paces',
            'Particularly low or high voice',
            'Prone to predictions of doom',
            'Prone to singing, humming, or whistling quietly',
            'Slurs words, lisps, or stutters',
            'Speaks in rhyme or some other peculiar way',
            'Speaks Loudly',
            'Squints',
            'Stares into the distance',
            'Taps fingers',
            'Twirls hair or tugs on beard',
            'Uses colorful oaths andexclamations',
            'Uses flowery speech or long words',
            'Whispers',
        ],
    },

    Traits = {
        1: [
            'Abrupt',
            'Absentminded',
            'Accessible',
            'Active',
            'Adaptable',
            'Adventurous',
            'Aggressive',
            'Agreeable',
            'Aimless',
            'Airy',
            'Alert',
            'Aloof',
            'Ambitious',
            'Amiable',
            'Amoral',
            'Angry',
            'Anxious',
            'Apathetic',
            'Appreciative',
            'Arbitrary',
            'Argumentative',
            'Arrogant',
            'Articulate',
            'Artificial',
            'Ascetic',
            'Asocial',
            'Aspiring',
            'Assertive',
            'Authoritarian',
            'Balanced',
            'Barbaric',
            'Benevolent',
            'Bewildered',
            'Big-thinking',
            'Biosterous',
            'Bizarre',
            'Bland',
            'Blunt',
            'Blustering',
            'Boyish',
            'Breezy',
            'Businesslike',
            'Busy',
            'Calculating',
            'Callous',
            'Calm',
            'Cantakerous',
            'Capable',
            'Captivating',
            'Careless',
            'Caring',
            'Casual',
            'Cautious',
            'Challenging',
            'Charming',
            'Charmless',
            'Cheerful',
            'Childish',
            'Chummy',
            'Clear-headed',
            'Clever',
            'Clumsy',
            'Coarse',
            'Cold',
            'Colorful',
            'Companionly',
            'Compassionate',
            'Competitive',
            'Complacent',
            'Complaintive',
            'Complex',
            'Compulsive',
            'Conceited',
            'Conciliatory',
            'Condemnatory',
            'Confident',
            'Confidential',
            'Conformist',
            'Confused',
            'Conscientious',
            'Conservative',
            'Considerate',
            'Contemplative',
            'Contemptible',
            'Contradictory',
            'Cooperative',
            'Courageous',
            'Courteous',
            'Cowardly',
            'Crafty',
            'Crazy',
            'Creative',
            'Crisp',
            'Critical',
            'Cruel',
            'Cultured',
            'Curious',
            'Cute',
            'Cynical',
            'Debonair',
            'Decadent',
            'Deceitful',
            'Decent',
            'Deceptive',
            'Decisive',
            'Dedicated',
            'Delicate',
            'Demanding',
            'Desperate',
            'Determined',
            'Devious',
            'Difficult',
            'Dignified',
            'Disciplined',
            'Disconcerting',
            'Discontented',
            'Discouraging',
            'Discourteous',
            'Discreet',
            'Dishonest',
            'Disloyal',
            'Disobedient',
            'Disorderly',
            'Disorganized',
            'Disrespectful',
            'Disruptive',
            'Distractible',
            'Dogmatic',
            'Dominating',
            'Domineering',
            'Dramatic',
            'Dreamy',
            'Droll',
            'Dry',
            'Dull',
            'Dutiful',
            'Earnest',
            'Earthy',
            'Easily Discouraged',
            'Educated',
            'Effeminate',
            'Efficient',
            'Egocentric',
            'Elegant',
            'Eloquent',
            'Emotional',
            'Empathetic',
            'Energetic',
            'Enervated',
            'Enigmatic',
            'Enthusiastic',
            'Envious',
            'Erratic',
            'Excitable',
            'Extravagant',
            'Extreme',
            'Fair',
            'Faithful',
            'Faithless',
            'False',
            'Familial',
            'Fanatical',
            'Fanciful',
            'Farsighted',
            'Fatalistic',
            'Fawning',
            'Fearful',
            'Fickle',
            'Fiery',
            'Firm',
            'Fixed',
            'Flamboyant',
            'Flexible',
            'Focused',
            'Folksy',
            'Foolish',
            'Forecful',
            'Forgetful',
            'Forgiving',
            'Formal',
            'Forthright',
            'Fraudulent',
            'Freethinking',
            'Friendly',
            'Frightening',
            'Frivolous',
            'Frugal',
            'Fun-loving',
            'Gallant',
            'Generous',
            'Gentle',
            'Genuine',
            'Glamorous',
            'Gloomy',
            'Good-natured',
            'Graceless',
            'Gracious',
            'Grand',
            'Greedy',
            'Grim',
            'Guileless',
            'Gullible',
            'Hardworking',
            'Hateful',
            'Haughty',
            'Healthy',
            'Hearty',
            'Hedonistic',
            'Helpful',
            'Hesitant',
            'Hidebound',
            'High-handed',
            'High-minded',
            'High-spirited',
            'Honest',
            'Honorable',
            'Hostile',
            'Hot-tempered',
            'Humble',
            'Humorous',
            'Huried',
            'Idealistic',
            'Idiosyncratic',
            'Ignorant',
            'Imaginative',
            'Imitative',
            'Impassive',
            'Impatient',
            'Impersonal',
            'Impractical',
            'Impressionable',
            'Impressive',
            'Imprudent',
            'Impulsive',
            'Inconsiderate',
            'Incorruptible',
            'Incurious',
            'Indecisive',
            'Independent',
            'Individualistic',
            'Indulgent',
            'Inhibited',
            'Innovative',
            'Inoffensive',
            'Insecure',
            'Insensitive',
            'Insightful',
            'Insincere',
            'Insulting',
            'Intelligent',
            'Intolerant',
            'Intuitive',
            'Irascible',
            'Irrational',
            'Irresponsible',
            'Irreverent',
            'Irritable',
            'Kind',
            'Knowledge',
            'Lazy',
            'Leisurely',
            'Liberal',
            'Logical',
            'Loquacious',
            'Lovable',
            'Loyal',
            'Magnanimous ',
            'Malicious',
            'Mannered',
            'Mannerless',
            'Masculine (Manly)',
            'Maternal',
            'Maticulous',
            'Mature',
            'Mawkish',
            'Meddlesome',
            'Melancholic',
            'Mellow',
            'Merciful',
            'Mercyless',
            'Messy',
            'Methodical',
            'Miserable',
            'Misguided',
            'Mistaken',
            'Moderate',
            'Modern',
            'Modest',
            'Money-minded',
            'Monstrous',
            'Moody',
            'Morbid',
            'Mystical',
            'Naive',
            'Narcissistic',
            'Narrow-minded',
            'Natty',
            'Neat',
            'Neglectful',
            'Neurotic',
            'Neutral',
            'Nihilistic',
            'Nonauthoritarian',
            'Noncommittal',
            'Noncompetitive',
            'Obedient',
            'Objective',
            'Obnoxious',
            'Observant',
            'Obsessive',
            'Obvious',
            'Odd',
            'Open',
            'Opinionated',
            'Opportunistic',
            'Oppressed',
            'Optimistic',
            'Orderly',
            'Ordinary',
            'Organized',
            'Outrageous',
            'Outspoken',
            'Overimaginative',
            'Painstaking',
            'Paranoid',
            'Passionate',
            'Passive',
            'Paternalistic',
            'Patient',
            'Patriotic',
            'Peaceful',
            'Perceptive',
            'Perfectionist',
            'Personable',
            'Persuasive',
            'Perverse',
            'Petty',
            'Physical',
            'Placid',
            'Playful',
            'Plodding',
            'Polished',
            'Political',
            'Pompous',
            'Ponderous',
            'Popular',
            'Possessive',
            'Power-hungry',
            'Practical',
            'Precise',
            'Predatory',
            'Predictable',
            'Prejudiced',
            'Preoccupied',
            'Presumptuous',
            'Pretentious',
            'Prim',
            'Principled',
            'Private',
            'Procrastinating',
            'Progressive',
            'Protective',
            'Proud',
            'Prudent',
            'Pruposeful',
            'Punctual',
            'Questioning',
            'Quiet',
            'Rational',
            'Reactionary',
            'Reactive',
            'Realistic',
            'Reflective',
            'Regimental',
            'Regretful',
            'Relaxed',
            'Reliable',
            'Religious',
            'Repentant',
            'Repressed',
            'Resentful',
            'Reserved',
            'Resourceful',
            'Respectful',
            'Responsible',
            'Restrained',
            'Reverential',
            'Rigid',
            'Ritualistic',
            'Romantic',
            'Rowdy',
            'Rude',
            'Rustic',
            'Sadistic',
            'Sage',
            'Sanctimonious',
            'Sane',
            'Sarcastic',
            'Scheming',
            'Scholarly',
            'Scornful',
            'Scrupulous',
            'Secretive',
            'Sedentary',
            'Self-conscious',
            'Self-critical',
            'Self-defacing',
            'Self-denying',
            'Self-indulgent',
            'Selfish',
            'Selfless',
            'Self-reliant',
            'Self-sufficent',
            'Sensitive',
            'Sentimental',
            'Serious',
            'Shallow',
            'Sharing',
            'Shortsighted',
            'Shrewd',
            'Shy',
            'Silly',
            'Simple',
            'Single-minded',
            'Skeptical',
            'Skillful',
            'Sloppy',
            'Slow',
            'Sly',
            'Small-thinking',
            'Smooth',
            'Sober',
            'Sociable',
            'Solemn',
            'Solid',
            'Solitary',
            'Sophisticated',
            'Spontaneous',
            'Sporting',
            'Stable',
            'Steadfast',
            'Steady',
            'Steely',
            'Stern',
        ],
    },

    Ideals = {
        1: [
            'Aspiration',
            'Balance',
            'Beauty',
            'Change',
            'Charity',
            'Community',
            'Creativity',
            'Discovery',
            'Domination',
            'Fairness',
            'Freedom',
            'Glory',
            'Greater Good',
            'Greed',
            'Honor',
            'Independance',
            'Knowledge',
            'Life',
            'Live and let live',
            'Logic',
            'Might',
            'Moderation',
            'Nation',
            'Neutrality',
            'No Limits',
            'Pain',
            'People',
            'Redemption',
            'Respect',
            'Responsibility',
            'Retribution',
            'Self Sacrifice',
            'Self-knowledge',
            'Slaughter',
            'Tradiion',
            'Whimsy',
        ],
    },

    Bonds = {
        1: [
            'A powerful person killed someone I love. Some day soon, I’ll have my revenge.',
            'A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.',
            'I escaped my life of poverty by robbing an important person, and I’m wanted for it.',
            'It is my duty to provide children to sustain my tribe.',
            'My house is my Family. I would do anything for it.',
            'My Instrument is my most treasured possession, and it reminds me of someone I love.',
            'My loyalty to my sovereign is unwavering.',
            'Someone stole my precious Instrument, and someday I’ll get it back.',
            'An injury to the unspoiled Wilderness of my home is an injury to me.',
            'Captivated by a romantic interest',
            'Dedicated to fulfilling a personal life goal',
            'Drawn to a special place',
            'Everything I do is for the common people.',
            'I am in love with the heir of a Family that my Family despises.',
            'I come from a noble Family, and one day I’ll reclaim my lands and title from those who stole them from me.',
            'I created a great work for someone, and then found them unworthy to receive it. I’m still looking for someone worthy.',
            'I fight for those who cannot fight for themselves.',
            'I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about.',
            'I have a Family, but I have no idea where they are. One day, I hope to see them again.',
            'I have an ancient text that holds Terrible Secrets that must not fall into the wrong hands.',
            'I idolize a hero of the old tales and measure my deeds against that person’s.',
            'I love someone from another house, but the relationship is forbidden.',
            'I owe a debt I can never repay to the person who took pity on me.',
            'I owe everything to my mentor—a horrible person who’s probably rotting in jail somewhere.',
            'I owe my guild a great debt for forging me into the person I am today.',
            'I own my life to the priest who took me in when my Parents died.',
            'I owe my Survival to another urchin who taught me to live on the streets.',
            'I protect those who cannot protect themselves.',
            'I pursue Wealth to secure someone’s love.',
            'I sponsor an orphanage to keep others from enduring what I was forced to endure.',
            'I suffer awful visions of a coming Disaster and will do anything to prevent it.',
            'I swindled and ruined a person who didn’t deserve it. I seek to atone for my misdeeds but might never be able to forgive myself.',
            'I want to be famous, whatever it takes.',
            'I was cheated out of my fair share of the profits, and I want to get my due.',
            'I will do anything to protect the Temple where I served.',
            'I will do anything to prove myself superior to my hated rival.',
            'I will face any Challenge to win the approval of my Family.',
            'I will someday get revenge on the corrupt Temple Hierarchy who branded me a heretic.',
            'I worked the land, I love the land, and I will protect the land.',
            'I wish my childhood sweetheart had come with me to persue my destiny.',
            'I would die to recover an ancient relic of my faith that was lost long ago.',
            'I would do anything for my old Mentor.',
            'I would do anything for the other members of my old troupe.',
            'I would still lay down my life for the people I served with.',
            'I’ll always remember my first home.',
            'I’ll never forget the crushing defeat my company suffered or the enemies who dealt it.',
            'I’m guilty of a terrible crime. I hope I can redeem myself for it.',
            'I’m loyal to my Leader first, everything else second.',
            'I’m trying to pay off an old debt I owe to a generous Benefactor.',
            'I’ve been searching my whole life for the answer to a certain question.',
            'I'm determined to impress the leaders of my house, and to become a leader myself.',
            'Loyal to a benefactor, patron, or employer',
            'My Family, clan, or tribe is the most important thing in my life, even when they are far from me.',
            'My honor is my life.',
            'My house’s alliance with another noble Family must be sustained at all costs.',
            'My ill-gotten gains go to support my Family.',
            'My life’s work is a series of tomes related to a specific field of lore.',
            'My tools are symbols of my past life, and I carry them so that I will never forget my roots.',
            'My town or city is my home, and I’ll fight to defend it.',
            'No one else should have to endure the hardships I’ve been through.',
            'Nothing is more important than the other members of my Family.',
            'Nothing is more important than the other members of my hermitage, order, or association.',
            'One day I will return to my guild and prove that I am the greatest artisan of them all.',
            'Out for revenge',
            'Protective of a sentimental keepsake',
            'Protective of close family members',
            'Protective of colleagues or compatriots',
            'Protective over a valuable possession',
            'Someone I loved died because of I mistake I made. That will never happen again.',
            'Someone saved my life on the battlefield. To this day, I will never leave a friend behind.',
            'Something important was taken from me, and I aim to steal it back.',
            'Somewhere out there, I have a child who doesn’t know me. I’m making the world better for him or her.',
            'The workshop where I learned my trade is the most important place in the world to me.',
            'Those who fight beside me are those worth dying for.',
        ],
    },

    Fears = {
        1: [
            'A relative Finding them',
            'Being poor',
            'Dying',
            'Fear of the unknown',
            'Loosing their status',
            'Their true identity being discovered',
            'Trusting others',
        ],
    },

    Superstitions = {
        1: [
            'A beginner will always have good luck: beginner’s luck',
            'A bird that comes in your window brings bad luck',
            'A black cat crossing one's path is bad luck',
            'A cat has nine lives',
            'A cricket in the house brings good luck',
            'A drowned woman floats face up and a drowned man floats face down',
            'A person cannot drown before going under three times',
            'A Priest in the street is a bad omen and whispers or signs of protection should be made',
            'A rabbit’s foot brings good luck',
            'A sailor wearing an earring cannot drown',
            'After receiving a container of food the container should never be returned empty (place your coins in your bowl or mug in a tavern)',
            'An acorn at the window can keep lightning out of the house',
            'An animal crossing one's path heading in a specific direction is bad luck',
            'An apple a day keeps the doctor away',
            'An itchy palm means money will come your way',
            'An owl flying over a house or camp is a sign of doom',
            'At the end of a rainbow is a pot of gold',
            'Bad luck comes in threes',
            'Breaking a mirror brings seven years of bad luck',
            'Clothes worn inside out will bring good luck',
            'Cold hands means a warm heart',
            'Crossing your fingers helps to avoid bad luck and helps a wish come true',
            'Eating fish makes you smart',
            'Evil spirits cannot harm you when you are standing in a circle',
            'Failing to respond to a letter is bad luck',
            'Garlic protects from evil spirits and vampires',
            'Giving a clock as a gift is saying their time death is near',
            'Hanging a horseshoe with the ends pointing down is bad luck',
            'If the bottom of your feet itch: you will make a trip',
            'If you shiver someone is casting a shadow on your grave',
            'It is bad luck to chase someone with a broom',
            'It is bad luck to sing at the table',
            'It is bad luck to sleep on a table',
            'It is unlucky to rock an empty rocking chair',
            'It's bad luck to put clothing on inside out; To reverse the bad luck you must immediately put it on right then have a friend hit you',
            'Mention of the word "longtail" or referring to a rodent will bring them',
            'Opening an umbrella while indoors is bad luck',
            'Our fate is written in the stars',
            'Pointing at a rainbow will bring good luck',
            'Pointing towards feces is bad luck',
            'Ravens crows and magpies are signs of doom',
            'Shoes or a hat on a table is bad luck',
            'Spilling salt or another material is bad luck',
            'Step on a crack & break your mother’s back',
            'Superstitious about a specific number',
            'Superstitious of a day',
            'Throwing rocks into the wind protects from evil',
            'Thunderstorms are harbingers of doom',
            'To drop a dishcloth means bad luck is coming',
            'To drop a fork means a woman will visit',
            'To drop a knife means a man will visit',
            'To drop a spoon means a child will visit',
            'To find a four-leaf clover is to find good luck',
            'To find a horseshoe brings good luck',
            'To give someone a purse or wallet without money in it will bring that person bad luck',
            'To kill an albatross is to cause bad luck to the ship and all upon it',
            'Toads cause warts',
            'Viewing one's doppelgänger is considered a harbinger of bad luck',
            'Walking under a ladder brings bad luck',
            'Warm hands means a cold heart',
            'Wearing your birthstone will bring you good luck',
            'When a dog or wolf howls then death is near',
            'Wishing someone "Good Luck" is bad luck',
            'You can break a bad luck spell by turning seven times in a clockwise circle',
            'You must get out of bed on the same side you got in on or you will have bad luck',
        ],
    },

    Appearance = {
        1: [
            'Bald',
            'Birthmark',
            'Braided beard or hair',
            'Distinctive jewelry: earrings, necklace, circlet, bracelets',
            'Distinctive nose',
            'Distinctive posture (crooked or rigid)',
            'Exceptionally beautiful',
            'Exceptionally ugly',
            'Flamboyant or outlandish clothing',
            'Formal clean clothing',
            'Missing Teeth',
            'Nervous eye twitch',
            'Piercings',
            'Pronounced scar',
            'Ragged dirty clothing',
            'Tattoos',
            'Unusual eye color or two different colors',
            'Unusual skin color',
        ],
    },

    Rank = {
        1: [
            'Apprentice',
            'Journeyman',
            'Master',
        ],
    },

    Flaw or Secret = {
        1: [
            'Arrogance',
            'Enjoyes decadent pleasures',
            'Envies another creature's possessions or station',
            'Foolhardy bravery',
            'Forbidden love or susceptibility to romance',
            'Has a powerful enemy',
            'Overpowering greed',
            'Possession of forbidden lore',
            'Prone to rage',
            'Secret crime or misdeed',
            'Shameful or scandalous history',
            'Specific phobia',
        ],
    },

    Talent = {
        1: [
            'Draws beautifully',
            'Drinks everyone under the table',
            'Expert carpenter',
            'Expert cook',
            'Expert dart thrower and rock skipper',
            'Expert juggler',
            'Great at impersonations',
            'Great at one game', 							**GAME**
            'Great at solving puzzles',
            'Great with animals',
            'Great with children',
            'Knows thieves’ cant',
            'Paints beautifully',
            'Perfect memory',
            'Plays a musicale instrument',
            'Sings beautifully',
            'Skilled actor and master of disguise',
            'Skilled dancer',
            'Speaks several languages fluently',
            'Unbelievably lucky',
        ],
    },

    Game = {
        1: [
            'Dragon Chess',
            'Poker',
            'High Draw',
            'Backgamon',
            'Darts',
            'Boulder Parchment Shears',
            'Tic Tac Toe',
            'Low Draw',
            'Spades',
            'Hearts',
            'Euker',
            'Cards',
            'Dice',
            'Craps',
        ],
    },

    Class = {
        1: [
            { roll: range(1,10), result: "Guild Member" },				**GUILD**
            { roll: range(11,15), result: "Adventurer" },
            { roll: range(16,20), result: "Baker" },
            { roll: range(21,28), result: "Butcher" },
            { roll: range(29,43), result: "Commoner" },
            { roll: range(44,48), result: "Criminal" },
            { roll: range(49,53), result: "Farmer" },
            { roll: range(54,56), result: "Highborn Merchant" },
            { roll: range(57,68), result: "Lowborn Merchant" },
            { roll: range(69,71), result: "Noble" },
            { roll: [1], result: "Poor Noble" },
            { roll: range(73,74), result: "Rich Noble" },
            { roll: range(75,79), result: "Servant" },
            { roll: range(80,87), result: "Smith" },
            { roll: range(88,92), result: "Tailor" },
            { roll: range(93,95), result: "Thug" },
            { roll: range(96,100), result: "Town Constable" },
        ],
    },

    Guild = {
        1: [
            { roll: [1], result: "Magic Users" },					**RANK**
            { roll: range(2,4), result: "Mason" },					**RANK**
            { roll: range(5,8), result: "Porters" },					**RANK**
            { roll: range(9,10), result: "Thieves'" },					**RANK**
        ],
    },




    Age = {
        1: [
            { roll: range(1,5), result: "Child" },
            { roll: range(6,25), result: "Young Adult" },
            { roll: range(26,60), result: "Adult" },
            { roll: range(61,90), result: "Middle Aged" },
            { roll: range(91,100), result: "Elder" },
        ],
    },

    Title = {
        1: [
            { roll: range(1,75), result: " " },
            { roll: range(76,78), result: "The Black" },
            { roll: range(79,81), result: "The Brave" },
            { roll: range(82,83), result: "The Cowardly" },
            { roll: [84], result: "The Fool" },
            { roll: range(85,87), result: "The Great" },
            { roll: [88], result: "The Hero" },
            { roll: range(89,91), result: "The Immense" },
            { roll: range(92,93), result: "The Joker" },
            { roll: [94], result: "The Madman" },
            { roll: [95], result: "The Shadow" },
            { roll: range(96,98), result: "The Small" },
            { roll: range(99,100), result: "The White" },
        ],
    },

    Alignment = {
        1: [
            { roll: range(1,25), result: "Chaotic Evil" },
            { roll: range(26,50), result: "Chaotic Good" },
            { roll: range(51,250), result: "Chaotic Neutral" },
            { roll: range(251,350), result: "Evil" },
            { roll: range(351,450), result: "Good" },
            { roll: range(451,475), result: "Lawful Evil" },
            { roll: range(476,500), result: "Lawful Good" },
            { roll: range(501,700), result: "Lawful Neutral" },
            { roll: range(701,1000), result: "Neutral" },
        ],
    },

    Ability = {
        High: [
            'Agile (Dexterity [[1t[HighRoll]]]), [[1t[LowAbilityDexterity]]]',
            'Born-Leader (Charisma [[1t[HighRoll]]]), [[1t[LowAbilityCharisma]]]',
            'Brawny (Strength [[1t[HighRoll]]]), [[1t[LowAbilityStrength]]]',
            'Forceful (Charisma [[1t[HighRoll]]]), [[1t[LowAbilityCharisma]]]',
            'Graceful (Dexterity [[1t[HighRoll]]]), [[1t[LowAbilityDexterity]]]',
            'Hale (Constitution [[1t[HighRoll]]]), [[1t[LowAbilityConstitution]]]',
            'Hardy (Constitution [[1t[HighRoll]]]), [[1t[LowAbilityConstitution]]]',
            'Healthy (Constitution [[1t[HighRoll]]]), [[1t[LowAbilityConstitution]]]',
            'Inquisitive (Intelligence [[1t[HighRoll]]]), [[1t[LowAbilityIntelligence]]]',
            'Insightful (Wisdom [[1t[HighRoll]]]), [[1t[LowAbilityWisdom]]]',
            'Learned (Intelligence [[1t[HighRoll]]]), [[1t[LowAbilityIntelligence]]]',
            'Lithe (Dexterity [[1t[HighRoll]]]), [[1t[LowAbilityDexterity]]]',
            'Perceptive (Wisdom [[1t[HighRoll]]]), [[1t[LowAbilityWisdom]]]',
            'Persuasive (Charisma [[1t[HighRoll]]]), [[1t[LowAbilityCharisma]]]',
            'Powerful (Strength [[1t[HighRoll]]]), [[1t[LowAbilityStrength]]]',
            'Spiritual (Wisdom [[1t[HighRoll]]]), [[1t[LowAbilityWisdom]]]',
            'Strong as an Ox (Strength [[1t[HighRoll]]]), [[1t[LowAbilityStrength]]]',
            'Studious (Intelligence [[1t[HighRoll]]]), [[1t[LowAbilityIntelligence]]]',
        ],
        Strength Low: [
            {roll: range(1,10), result: " " },
            {roll: [11], result:  "Absentminded (Wisdom [[1t[LowRoll]]])" },
            {roll: [12], result:  "Boring (Charisma [[1t[LowRoll]]])" },
            {roll: [13], result:  "Clumsy (Dexterity [[1t[LowRoll]]])" },
            {roll: [14], result:  "Dim-witted (Intelligence [[1t[LowRoll]]])" },
            {roll: [15], result:  "Dull (Charisma [[1t[LowRoll]]])" },
            {roll: [16], result:  "Fumbling (Dexterity [[1t[LowRoll]]])" },
            {roll: [17], result:  "Oblivious (Wisdom [[1t[LowRoll]]])" },
            {roll: [18], result:  "Pale (Constitution [[1t[LowRoll]]])" },
            {roll: [19], result:  "Sickly (Constitution [[1t[LowRoll]]])" },
            {roll: [20], result:  "Slow (Intelligence [[1t[LowRoll]]])" },
        ],
        Dexterity Low: [
            {roll: range(1,10), result: " " },
            {roll: [11], result:  "Absentminded (Wisdom [[1t[LowRoll]]])" },
            {roll: [12], result:  "Boring (Charisma [[1t[LowRoll]]])" },
            {roll: [13], result:  "Dim-witted (Intelligence [[1t[LowRoll]]])" },
            {roll: [14], result:  "Dull (Charisma [[1t[LowRoll]]])" },
            {roll: [15], result:  "Feeble (Strength [[1t[LowRoll]]])" },
            {roll: [16], result:  "Oblivious (Wisdom [[1t[LowRoll]]])" },
            {roll: [17], result:  "Pale (Constitution [[1t[LowRoll]]])" },
            {roll: [18], result:  "Scrawny (Strength [[1t[LowRoll]]])" },
            {roll: [19], result:  "Sickly (Constitution [[1t[LowRoll]]])" },
            {roll: [20], result:  "Slow (Intelligence [[1t[LowRoll]]])" },
        ],
        Constitution Low: [
            {roll: range(1,10), result: " " },
            {roll: [11], result:  "Absentminded (Wisdom [[1t[LowRoll]]])" },
            {roll: [12], result:  "Boring (Charisma [[1t[LowRoll]]])" },
            {roll: [13], result:  "Clumsy (Dexterity [[1t[LowRoll]]])" },
            {roll: [14], result:  "Dim-witted (Intelligence [[1t[LowRoll]]])" },
            {roll: [15], result:  "Dull (Charisma [[1t[LowRoll]]])" },
            {roll: [16], result:  "Feeble (Strength [[1t[LowRoll]]])" },
            {roll: [17], result:  "Fumbling (Dexterity [[1t[LowRoll]]])" },
            {roll: [18], result:  "Oblivious (Wisdom [[1t[LowRoll]]])" },
            {roll: [19], result:  "Scrawny (Strength [[1t[LowRoll]]])" },
            {roll: [20], result:  "Slow (Intelligence [[1t[LowRoll]]])" },
        ],
        Intelligence Low: [
            {roll: range(1,10), result: " " },
            {roll: [11], result:  "Absentminded (Wisdom [[1t[LowRoll]]])" },
            {roll: [12], result:  "Boring (Charisma [[1t[LowRoll]]])" },
            {roll: [13], result:  "Clumsy (Dexterity [[1t[LowRoll]]])" },
            {roll: [14], result:  "Dull (Charisma [[1t[LowRoll]]])" },
            {roll: [15], result:  "Feeble (Strength [[1t[LowRoll]]])" },
            {roll: [16], result:  "Fumbling (Dexterity [[1t[LowRoll]]])" },
            {roll: [17], result:  "Oblivious (Wisdom [[1t[LowRoll]]])" },
            {roll: [18], result:  "Pale (Constitution [[1t[LowRoll]]])" },
            {roll: [19], result:  "Scrawny (Strength [[1t[LowRoll]]])" },
            {roll: [20], result:  "Sickly (Constitution [[1t[LowRoll]]])" },
        ],
        Wisdom Low: [
            {roll: range(1,10), result: " " },
            {roll: [11], result:  "Boring (Charisma [[1t[LowRoll]]])" },
            {roll: [12], result:  "Clumsy (Dexterity [[1t[LowRoll]]])" },
            {roll: [13], result:  "Dim-witted (Intelligence [[1t[LowRoll]]])" },
            {roll: [14], result:  "Dull (Charisma [[1t[LowRoll]]])" },
            {roll: [15], result:  "Feeble (Strength [[1t[LowRoll]]])" },
            {roll: [16], result:  "Fumbling (Dexterity [[1t[LowRoll]]])" },
            {roll: [17], result:  "Pale (Constitution [[1t[LowRoll]]])" },
            {roll: [18], result:  "Scrawny (Strength [[1t[LowRoll]]])" },
            {roll: [19], result:  "Sickly (Constitution [[1t[LowRoll]]])" },
            {roll: [20], result:  "Slow (Intelligence [[1t[LowRoll]]])" },
        ],
        Charisma Low: [
            {roll: range(1,10), result: " " },
            {roll: [11], result:  "Absentminded (Wisdom [[1t[LowRoll]]])" },
            {roll: [12], result:  "Clumsy (Dexterity [[1t[LowRoll]]])" },
            {roll: [13], result:  "Dim-witted (Intelligence [[1t[LowRoll]]])" },
            {roll: [14], result:  "Feeble (Strength [[1t[LowRoll]]])" },
            {roll: [15], result:  "Fumbling (Dexterity [[1t[LowRoll]]])" },
            {roll: [16], result:  "Oblivious (Wisdom [[1t[LowRoll]]])" },
            {roll: [17], result:  "Pale (Constitution [[1t[LowRoll]]])" },
            {roll: [18], result:  "Scrawny (Strength [[1t[LowRoll]]])" },
            {roll: [19], result:  "Sickly (Constitution [[1t[LowRoll]]])" },
            {roll: [20], result:  "Slow (Intelligence [[1t[LowRoll]]])" },
        ],
        High Roll: [
            '14',
            '15',
            '16',
            '17',
            '18',
        ],
        Low Roll: [
            '4',
            '5',
            '6',
            '7',
            '8',
        ],
    },

    Human Name = {
        First: [
            'Human Male named Anlow',
            'Human Male named Arando',
            'Human Male named Bram',
            'Human Male named Cale',
            'Human Male named Dalkon',
            'Human Male named Daylen',
            'Human Male named Dodd',
            'Human Male named Dungarth',
            'Human Male named Dyrk',
            'Human Male named Eandro',
            'Human Male named Falken',
            'Human Male named Feck',
            'Human Male named Fenton',
            'Human Male named Gryphero',
            'Human Male named Hagar',
            'Human Male named Jeras',
            'Human Male named Krynt',
            'Human Male named Lavant',
            'Human Male named Leyten',
            'Human Male named Madian',
            'Human Male named Malfie',
            'Human Male named Marku',
            'Human Male named Mekl',
            'Human Male named Nam',
            'Human Male named Navar',
            'Human Male named Nerl',
            'Human Male named Nilu',
            'Human Male named Ningy',
            'Human Male named Norr',
            'Human Male named Quentin',
            'Human Male named Semil',
            'Human Male named Sevenson',
            'Human Male named Steveren',
            'Human Male named Talfen',
            'Human Male named Tamond',
            'Human Male named Taran',
            'Human Male named Tavon',
            'Human Male named Tegan',
            'Human Male named Vanan',
            'Human Male named Vincent',
            'Human Female named Azura',
            'Human Female named Brey',
            'Human Female named Hallan',
            'Human Female named Kasaki',
            'Human Female named Lorelei',
            'Human Female named Mirabel',
            'Human Female named Pharana',
            'Human Female named Remora',
            'Human Female named Rosalyn',
            'Human Female named Sachil',
            'Human Female named Saidi',
            'Human Female named Tanika',
            'Human Female named Tura',
            'Human Female named Tylsa',
            'Human Female named Vencia',
            'Human Female named Xandrilla',
        ],
        Last: [
            'Arkalis',
            'Arkalis',
            'Armanci',
            'Bilger',
            'Blackstrand',
            'Brightwater',
            'Carnavon',
            'Caskajaro',
            'Coldshore',
            'Coyle',
            'Cresthill',
            'Cuttlescar',
            'Daargen',
            'Dalicarlia',
            'Danamark',
            'Donoghan',
            'Drumwind',
            'Dunhall',
            'Ereghast',
            'Falck',
            'Fallenbridge',
            'Faringray',
            'Fletcher',
            'Fryft',
            'Goldrudder',
            'Grantham',
            'Graylock',
            'Gullscream',
            'Hindergrass',
            'Iscalon',
            'Kreel',
            'Kroft',
            'Lamoth',
            'Leerstrom',
            'Lynchfield',
            'Moonridge',
            'Netheridge',
            'Oakenheart',
            'Pyncion',
            'Ratley',
            'Redraven',
            'Revenmar',
            'Roxley',
            'Seratolva',
            'Shanks',
            'Shattermast',
            'Shaulfer',
            'Silvergraft',
            'Stavenger',
            'Stormchapel',
            'Strong',
            'Swiller',
            'Talandro',
            'Targana',
            'Towerfall',
            'Umbermoor',
            'Van Devries',
            'Van Gandt',
            'Van Hyden',
            'Varcona',
            'Varzand',
            'Voortham',
            'Vrye',
            'Webb',
            'Welfer',
            'Wilxes',
            'Wintermere',
            'Wygarthe',
            'Zatchet',
            'Zethergyll',
        ],
    },

    Half Elf Name = {
        First: [
            'Half-Elf Male named Anlow',
            'Half-Elf Male named Arando',
            'Half-Elf Male named Bram',
            'Half-Elf Male named Cale',
            'Half-Elf Male named Dalkon',
            'Half-Elf Male named Daylen',
            'Half-Elf Male named Dodd',
            'Half-Elf Male named Dungarth',
            'Half-Elf Male named Dyrk',
            'Half-Elf Male named Eandro',
            'Half-Elf Male named Falken',
            'Half-Elf Male named Feck',
            'Half-Elf Male named Fenton',
            'Half-Elf Male named Gryphero',
            'Half-Elf Male named Hagar',
            'Half-Elf Male named Jeras',
            'Half-Elf Male named Krynt',
            'Half-Elf Male named Lavant',
            'Half-Elf Male named Leyten',
            'Half-Elf Male named Madian',
            'Half-Elf Male named Malfie',
            'Half-Elf Male named Marku',
            'Half-Elf Male named Mekl',
            'Half-Elf Male named Nam',
            'Half-Elf Male named Navar',
            'Half-Elf Male named Nerl',
            'Half-Elf Male named Nilu',
            'Half-Elf Male named Ningy',
            'Half-Elf Male named Norr',
            'Half-Elf Male named Quentin',
            'Half-Elf Male named Semil',
            'Half-Elf Male named Sevenson',
            'Half-Elf Male named Steveren',
            'Half-Elf Male named Talfen',
            'Half-Elf Male named Tamond',
            'Half-Elf Male named Taran',
            'Half-Elf Male named Tavon',
            'Half-Elf Male named Tegan',
            'Half-Elf Male named Vanan',
            'Half-Elf Male named Vincent',
            'Half-Elf Female named Azura',
            'Half-Elf Female named Brey',
            'Half-Elf Female named Hallan',
            'Half-Elf Female named Kasaki',
            'Half-Elf Female named Lorelei',
            'Half-Elf Female named Mirabel',
            'Half-Elf Female named Pharana',
            'Half-Elf Female named Remora',
            'Half-Elf Female named Rosalyn',
            'Half-Elf Female named Sachil',
            'Half-Elf Female named Saidi',
            'Half-Elf Female named Tanika',
            'Half-Elf Female named Tura',
            'Half-Elf Female named Tylsa',
            'Half-Elf Female named Vencia',
            'Half-Elf Female named Xandrilla',
            'Half-Elf Female named Aryllan',
            'Half-Elf Female named Atalya',
            'Half-Elf Female named Ayrthwil',
            'Half-Elf Female named Irva',
            'Half-Elf Female named Lyfalia',
            'Half-Elf Female named Ronefel',
            'Half-Elf Female named Thirya',
            'Half-Elf Female named Velene',
            'Half-Elf Female named Venefiq',
            'Half-Elf Female named Zereni',
            'Half-Elf Male named Alarcion',
            'Half-Elf Male named Alathar',
            'Half-Elf Male named Ariandar',
            'Half-Elf Male named Arromar',
            'Half-Elf Male named Borel',
            'Half-Elf Male named Bvachan',
            'Half-Elf Male named Carydion',
            'Half-Elf Male named Elgoth',
            'Half-Elf Male named Farlien',
            'Half-Elf Male named Ferel',
            'Half-Elf Male named Gaerlan',
            'Half-Elf Male named Iafalior',
            'Half-Elf Male named Kaelthorn',
            'Half-Elf Male named Laethan',
            'Half-Elf Male named Leliar',
            'Half-Elf Male named Leodor',
            'Half-Elf Male named Lorak',
            'Half-Elf Male named Lorifir',
            'Half-Elf Male named Morian',
            'Half-Elf Male named Oleran',
            'Half-Elf Male named Rylef',
            'Half-Elf Male named Savian',
            'Half-Elf Male named Seylas',
            'Half-Elf Male named Tevior',
            'Half-Elf Male named Veyas',
        ],
        Last: [
            'Arkalis',
            'Arkalis',
            'Armanci',
            'Bilger',
            'Blackstrand',
            'Brightwater',
            'Carnavon',
            'Caskajaro',
            'Coldshore',
            'Coyle',
            'Cresthill',
            'Cuttlescar',
            'Daargen',
            'Dalicarlia',
            'Danamark',
            'Donoghan',
            'Drumwind',
            'Dunhall',
            'Ereghast',
            'Falck',
            'Fallenbridge',
            'Faringray',
            'Fletcher',
            'Fryft',
            'Goldrudder',
            'Grantham',
            'Graylock',
            'Gullscream',
            'Hindergrass',
            'Iscalon',
            'Kreel',
            'Kroft',
            'Lamoth',
            'Leerstrom',
            'Lynchfield',
            'Moonridge',
            'Netheridge',
            'Oakenheart',
            'Pyncion',
            'Ratley',
            'Redraven',
            'Revenmar',
            'Roxley',
            'Seratolva',
            'Shanks',
            'Shattermast',
            'Shaulfer',
            'Silvergraft',
            'Stavenger',
            'Stormchapel',
            'Strong',
            'Swiller',
            'Talandro',
            'Targana',
            'Towerfall',
            'Umbermoor',
            'Van Devries',
            'Van Gandt',
            'Van Hyden',
            'Varcona',
            'Varzand',
            'Voortham',
            'Vrye',
            'Webb',
            'Welfer',
            'Wilxes',
            'Wintermere',
            'Wygarthe',
            'Zatchet',
            'Zethergyll',
            'Autumnloft',
            'Balefrost',
            'Briarfell',
            'Evenwind',
            'Graytrails',
            'Mooncairn',
            'Riverwall',
            'Stormwolf',
            'Summergale',
            'Sunshadow',
            'Woodenhawk',
        ],
    },

    Elf Name = {
        First: [
            'Elven Female named Aryllan',
            'Elven Female named Atalya',
            'Elven Female named Ayrthwil',
            'Elven Female named Irva',
            'Elven Female named Lyfalia',
            'Elven Female named Ronefel',
            'Elven Female named Thirya',
            'Elven Female named Velene',
            'Elven Female named Venefiq',
            'Elven Female named Zereni',
            'Elven Male named Alarcion',
            'Elven Male named Alathar',
            'Elven Male named Ariandar',
            'Elven Male named Arromar',
            'Elven Male named Borel',
            'Elven Male named Bvachan',
            'Elven Male named Carydion',
            'Elven Male named Elgoth',
            'Elven Male named Farlien',
            'Elven Male named Ferel',
            'Elven Male named Gaerlan',
            'Elven Male named Iafalior',
            'Elven Male named Kaelthorn',
            'Elven Male named Laethan',
            'Elven Male named Leliar',
            'Elven Male named Leodor',
            'Elven Male named Lorak',
            'Elven Male named Lorifir',
            'Elven Male named Morian',
            'Elven Male named Oleran',
            'Elven Male named Rylef',
            'Elven Male named Savian',
            'Elven Male named Seylas',
            'Elven Male named Tevior',
            'Elven Male named Veyas',
        ],
        Last: [
            'Autumnloft',
            'Balefrost',
            'Briarfell',
            'Evenwind',
            'Graytrails',
            'Mooncairn',
            'Riverwall',
            'Stormwolf',
            'Summergale',
            'Sunshadow',
            'Woodenhawk',
        ],
    },

    Dwarf Name = {
        First: [
            'Dwarven Female named Beyla',
            'Dwarven Female named Fenryl',
            'Dwarven Female named Grenenzel',
            'Dwarven Female named Krystolari',
            'Dwarven Female named Lokara',
            'Dwarven Female named Lurka',
            'Dwarven Female named Marnia',
            'Dwarven Female named Praxana',
            'Dwarven Female named Rokel',
            'Dwarven Female named Roksana',
            'Dwarven Female named Thurlfara',
            'Dwarven Female named Vauldra',
            'Dwarven Female named Veklani',
            'Dwarven Female named Vronwe',
            'Dwarven Female named Zebel',
            'Dwarven Male named Agaro',
            'Dwarven Male named Arnan',
            'Dwarven Male named Auxlan',
            'Dwarven Male named Avamir',
            'Dwarven Male named Baelnar',
            'Dwarven Male named Balfam',
            'Dwarven Male named Bariken',
            'Dwarven Male named Borkûl',
            'Dwarven Male named Darkûl',
            'Dwarven Male named Dolmen',
            'Dwarven Male named Dyrnar',
            'Dwarven Male named Erag',
            'Dwarven Male named Ezegan',
            'Dwarven Male named Ferrek',
            'Dwarven Male named Garmûl',
            'Dwarven Male named Ghorvas',
            'Dwarven Male named Glint',
            'Dwarven Male named Grimmalk',
            'Dwarven Male named Haeltar',
            'Dwarven Male named Halagmar',
            'Dwarven Male named Halzar',
            'Dwarven Male named Hlant',
            'Dwarven Male named Korlag',
            'Dwarven Male named Krag',
            'Dwarven Male named Krim',
            'Dwarven Male named Lurtrum',
            'Dwarven Male named Malagar',
            'Dwarven Male named Maulnar',
            'Dwarven Male named Melgar',
            'Dwarven Male named Morak',
            'Dwarven Male named Orobok',
            'Dwarven Male named Rogath',
            'Dwarven Male named Roken',
            'Dwarven Male named Rozag',
            'Dwarven Male named Sabakzar',
            'Dwarven Male named Sharak',
            'Dwarven Male named Smethykk',
            'Dwarven Male named Swargar',
            'Dwarven Male named Thorbalt',
            'Dwarven Male named Thorin',
            'Dwarven Male named Tredigar',
            'Dwarven Male named Vabûl',
            'Dwarven Male named Vistrum',
            'Dwarven Male named Wolvar',
        ],
        Last: [
            'Ambershard',
            'Barrelhelm',
            'Copperhearth',
            'Deepmiddens',
            'Drakantal',
            'Evermead',
            'Garkalan',
            'Grimtor',
            'Hackshield',
            'Irongull',
            'Markolak',
            'Ramcrown',
            'Rockharvest',
            'Silvertarn',
            'Skandalor',
            'Zarkanan',
        ],
    },

    Halfling Name = {
        First: [
            'Halfling Female named Caliope',
            'Halfling Female named Emily',
            'Halfling Female named Piper',
            'Halfling Female named Rixi',
            'Halfling Female named Sabretha',
            'Halfling Female named Teg',
            'Halfling Female named Tilly',
            'Halfling Female named Toira',
            'Halfling Female named Vexia',
            'Halfling Female named Vil',
            'Halfling Female named Vzani',
            'Halfling Female named Zanthe',
            'Halfling Female named Ziza',
            'Halfling Male named Arthan',
            'Halfling Male named Carvin',
            'Halfling Male named Corby',
            'Halfling Male named Cullen',
            'Halfling Male named Egen',
            'Halfling Male named Ernest',
            'Halfling Male named Gedi',
            'Halfling Male named Heron',
            'Halfling Male named Jeryl',
            'Halfling Male named Keffen',
            'Halfling Male named Kylem',
            'Halfling Male named Kynt',
            'Halfling Male named Leskyn',
            'Halfling Male named Neff',
            'Halfling Male named Orne',
            'Halfling Male named Quarrel',
            'Halfling Male named Rabbit',
            'Halfling Male named Rilkin',
            'Halfling Male named Snakebait',
            'Halfling Male named Tarfen',
            'Halfling Male named Titch',
            'Halfling Male named Tuck',
            'Halfling Male named Whim',
        ],
        Last: [
            'Angler',
            'Battlestone',
            'Blackwater',
            'Daggersharp',
            'Deepstrider',
            'Hollowpot',
            'Puddle',
            'Raftmite',
            'Silverfin',
            'Skiprock',
            'Tanglestrand',
            'Tricker',
            'Willowrush',
            'Yellowcrane',
        ],
    },

    Dragonborn Name = {
        First: [
            'Dragonborn Female named Artana',
            'Dragonborn Female named Kalas',
            'Dragonborn Female named Khagra',
            'Dragonborn Female named Leytra',
            'Dragonborn Female named Myrka',
            'Dragonborn Female named Naya',
            'Dragonborn Female named Sarcha',
            'Dragonborn Female named Shirren',
            'Dragonborn Female named Sirivistra',
            'Dragonborn Female named Sufana',
            'Dragonborn Female named Tamara',
            'Dragonborn Female named Vrumadi',
            'Dragonborn Female named Zovra',
            'Dragonborn Male named Andujar',
            'Dragonborn Male named Armagan',
            'Dragonborn Male named Armek',
            'Dragonborn Male named Arzan',
            'Dragonborn Male named Axaran',
            'Dragonborn Male named Belaxarim',
            'Dragonborn Male named Brevarr',
            'Dragonborn Male named Djemidor',
            'Dragonborn Male named Draxan',
            'Dragonborn Male named Fayal',
            'Dragonborn Male named Grax',
            'Dragonborn Male named Inzul',
            'Dragonborn Male named Iojad',
            'Dragonborn Male named Khiraj',
            'Dragonborn Male named Kreytzen',
            'Dragonborn Male named Lejek',
            'Dragonborn Male named Mar',
            'Dragonborn Male named Nazir',
            'Dragonborn Male named Nedam',
            'Dragonborn Male named Nevek',
            'Dragonborn Male named Ravaran',
            'Dragonborn Male named Razaan',
            'Dragonborn Male named Sarax',
            'Dragonborn Male named Sarram',
            'Dragonborn Male named Savaxis',
            'Dragonborn Male named Siangar',
            'Dragonborn Male named Sirizan',
            'Dragonborn Male named Sunan',
            'Dragonborn Male named Szuran',
            'Dragonborn Male named Tajan',
            'Dragonborn Male named Tamajon',
            'Dragonborn Male named Tenahn',
            'Dragonborn Male named Toxal',
            'Dragonborn Male named Tzegyr',
            'Dragonborn Male named Vantajar',
            'Dragonborn Male named Vharkus',
            'Dragonborn Male named Xafiq',
            'Dragonborn Male named Zarkhil',
        ],
        Last: [
            'Arazandro',
            'Arkhor',
            'Asha-Naga',
            'Astaryntha',
            'Avandra',
            'Bharzim',
            'Bhez-Rizma',
            'Calomaar',
            'Chethel',
            'Corellon',
            'Damilor',
            'Dweomer',
            'Elyndri',
            'Ghorzaar',
            'Graethan',
            'Grimbol',
            'Halendros',
            'Hareth',
            'Irthos',
            'Kara-Vaji',
            'Karthang',
            'Kasha',
            'Kavath',
            'Khahar',
            'Koalinthas',
            'Kral-Tajir',
            'Krimilvin',
            'Lantheon',
            'Libram',
            'Locathah',
            'Maal-Destir',
            'Malfier',
            'Mar-Turang',
            'Melora',
            'Mirasandra',
            'Morkoth',
            'Myrska',
            'Prallmar',
            'Rakal',
            'Rangoth',
            'Saerthzal',
            'Sehanine',
            'Shalastar',
            'Shara-Vaja',
            'Shensari',
            'Shevaya',
            'Skandalor',
            'Tamarion',
            'Tanishar',
            'Tano',
            'Tezmyr',
            'Tirah',
            'Turathi',
            'Vaazrus',
            'Varalan',
            'Ven’r',
            'Vostarika',
            'Yisek',
            'Zaetchan',
            'Zaetra',
            'Zarkanan',
            'Zhal',
        ],
    },

    Tiefling Name = {
        First: [
            'Tiefling Female named Affyria',
            'Tiefling Female named Cataclysmia',
            'Tiefling Female named Domitia',
            'Tiefling Female named Dorethau',
            'Tiefling Female named Excellence',
            'Tiefling Female named Hacari',
            'Tiefling Female named Iritra',
            'Tiefling Female named Lachira',
            'Tiefling Female named Levatra',
            'Tiefling Female named Mecretia',
            'Tiefling Female named Milvia',
            'Tiefling Female named Nericia',
            'Tiefling Female named Precious',
            'Tiefling Female named Rain',
            'Tiefling Female named Samantia',
            'Tiefling Female named Sunshine',
            'Tiefling Female named Tenerife',
            'Tiefling Female named Traya',
            'Tiefling Female named Velavia',
            'Tiefling Female named Zaidi',
            'Tiefling Female named Zethaya',
            'Tiefling Male named Ankhus',
            'Tiefling Male named Archidius',
            'Tiefling Male named Arkadi',
            'Tiefling Male named Armarius',
            'Tiefling Male named Armillius',
            'Tiefling Male named Balmoloch',
            'Tiefling Male named Calderax',
            'Tiefling Male named Cavian',
            'Tiefling Male named Cenereth',
            'Tiefling Male named Chorum',
            'Tiefling Male named Corynax',
            'Tiefling Male named Dacian',
            'Tiefling Male named Daelius',
            'Tiefling Male named Damaceus',
            'Tiefling Male named Decimeth',
            'Tiefling Male named Demedor',
            'Tiefling Male named Demerian',
            'Tiefling Male named Dynachus',
            'Tiefling Male named Grassus',
            'Tiefling Male named Halius',
            'Tiefling Male named Heleph',
            'Tiefling Male named Incirion',
            'Tiefling Male named Kalaradian',
            'Tiefling Male named Kamien',
            'Tiefling Male named Kazimir',
            'Tiefling Male named Kzandro',
            'Tiefling Male named Machem',
            'Tiefling Male named Maetheus',
            'Tiefling Male named Malfias',
            'Tiefling Male named Marchion',
            'Tiefling Male named Menerus',
            'Tiefling Male named Namazeus',
            'Tiefling Male named Nensis',
            'Tiefling Male named Prismeus',
            'Tiefling Male named Pyranikus',
            'Tiefling Male named Razortail',
            'Tiefling Male named Sejanus',
            'Tiefling Male named Severian',
            'Tiefling Male named Syken',
            'Tiefling Male named Tarkus',
            'Tiefling Male named Vaius',
            'Tiefling Male named Xerek',
            'Tiefling Male named Zeth',
            'Tiefling Male named Zevon',
        ],
        Last: [
            'Amarzian',
            'Carnago',
            'Domarien',
            'Iscitan',
            'Meluzan',
            'Menetrian',
            'Paradas',
            'Romazi',
            'Sarzan',
            'Serechor',
            'Shadowhorn',
            'Szereban',
            'Torzalan',
            'Trelenus',
            'Trevethor',
            'Tryphon',
            'Vadu',
            'Vrago',
        ],
    },

    Race = {
        Race Choice: [
            { roll: [1], result: [
                { type: "Human Name", die: "1", table: "First" },
                { type: "Human Name", die: "1", table: "Last" } },
            ] },
            { roll: [2], result: [
                { type: "Elf Name", die: "1", table: "First" },
                { type: "Elf Name", die: "1", table: "Last" } },
            ] },
            { roll: [3], result: [
                { type: "Half Elf Name", die: "1", table: "First" },
                { type: "Half Elf Name", die: "1", table: "Last" } },
            ] },
            { roll: [4], result: [
                { type: "Dwarf Name", die: "1", table: "First" },
                { type: "Dwarf Name", die: "1", table: "Last" } },
            ] },
            { roll: [5], result: [
                { type: "Dragonborn Name", die: "1", table: "First" },
                { type: "Dragonborn Name", die: "1", table: "Last" } },
            ] },
            { roll: [6], result: [
                { type: "Tiefling Name", die: "1", table: "First" },
                { type: "Tiefling Name", die: "1", table: "Last" } },
            ] },
        ],
    },
